#For full documentation of the parameters in this file, and a list of all the
#parameters available for TrajectoryPlannerROS, please see
#http://www.ros.org/wiki/base_local_planner

TrajectoryPlannerROS:
  #Set the acceleration limits of the robot
  acc_lim_theta: 3.2 
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  #Set the velocity limits of the robot
  max_vel_x: 1.65
  min_vel_x: 0.3 #0.17
  max_rotational_vel: 2.5
  # Depreciated # min_in_place_rotational_vel: 0.4
  min_in_place_vel_theta: 0.4

  max_vel_theta: 1.0 # Default 1.0
  min_vel_theta: -1.0 # Default -1.0
  min_in_place_vel_theta: 0.4 # Default 0.4

  #The velocity the robot will command when trying to escape from a stuck situation
  escape_vel: -0.1
  
  #For this example, we'll use a holonomic robot
  holonomic_robot: false

  #Set the tolerance on achieving a goal
  xy_goal_tolerance: 0.1 # Default: 0.10
  yaw_goal_tolerance: 0.05 # Default: 0.05

  #We'll configure how long and with what granularity we'll forward simulate trajectories
  sim_time: 1.0 # Default: 1
  sim_granularity: 0.025 # Default: 0.025


  #Parameters for scoring trajectories
  goal_distance_bias: 0.6
  path_distance_bias: 0.6
  occdist_scale: 0.01
  heading_lookahead: 0.325

  meter_scoring: true

